config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'pages#home'

  devise_for :instructors, path: "instructors", controllers: {
      sessions:      'instructors/sessions',
      passwords:     'instructors/passwords',
      registrations: 'instructors/registrations'
    }, path_names: { sign_up: 'touroku'}
    
  devise_for :members, controllers: {
    sessions:      'members/sessions',
    passwords:     'members/passwords',
    registrations: 'members/registrations'
  }
  
  resources :instructors, only: [:show]
  resources :members, only: [:show]
  
  resources :courses do
    resources :sections
    resources :subscriptions, only: [:create]
  end
  
  get '/purchase_history' => 'subscriptions#purchase_history'
end

app/views/shared/_devise_errors.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">

    <% resource.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>')
    <% end %>

  </script>
<% end %>

app/views/shared/_errors.html.erb
<% unless @course.errors.empty? %>
  <script type="text/javascript">
    <% @course.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_instructor_sidebar.html.erb
<nav class="navbar navbar-inverse sidebar" role="navigation">
    <div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand">講師ダッシュボード</a>
		</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li>
					<%= link_to root_path do %>
            <i style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></i> Home
          <% end %>
        </li>
        
       	<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Profile <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a>
					<ul class="dropdown-menu forAnimate" role="menu">
						<li><%= link_to 'プロフィールを編集', edit_instructor_registration_path %></li>
						<li><%= link_to '自分のプロフィールを見る', instructor_path(current_instructor.id) %></li>
					</ul>
				</li>
        
       	<li>
					<%= link_to courses_path do %>
            <i style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-book"></i> Course Edit
          <% end %>
        </li>
        
			</ul>
		</div>
	</div>
</nav>

<script>
	    function htmlbodyHeightUpdate(){
		var height3 = $( window ).height()
		var height1 = $('.nav').height()+50
		height2 = $('.main').height()
		if(height2 > height3){
			$('html').height(Math.max(height1,height3,height2)+10);
			$('body').height(Math.max(height1,height3,height2)+10);
		}
		else
		{
			$('html').height(Math.max(height1,height3,height2));
			$('body').height(Math.max(height1,height3,height2));
		}
		
	}
	$(document).ready(function () {
		htmlbodyHeightUpdate()
		$( window ).resize(function() {
			htmlbodyHeightUpdate()
		});
		$( window ).scroll(function() {
			height2 = $('.main').height()
  			htmlbodyHeightUpdate()
		});
	});
	
	
</script>

app/views/shared/_member_sidebar.html.erb
<nav class="navbar navbar-inverse sidebar" role="navigation">
    <div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand">生徒ダッシュボード</a>
		</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li>
					<%= link_to root_path do %>
            <i style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></i> Home
          <% end %>
        </li>
        
       	<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Profile <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a>
					<ul class="dropdown-menu forAnimate" role="menu">
						<li><%= link_to 'プロフィールを編集', edit_member_registration_path %></li>
						<li><%= link_to '自分のプロフィールを見る', member_path(current_member.id) %></li>
					</ul>
				</li>
        
       	<li>
					<%= link_to purchase_history_path do %>
            <i style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-book"></i> 購入済みのコース
          <% end %>
        </li>
        
			</ul>
		</div>
	</div>
</nav>

<script>
	    function htmlbodyHeightUpdate(){
		var height3 = $( window ).height()
		var height1 = $('.nav').height()+50
		height2 = $('.main').height()
		if(height2 > height3){
			$('html').height(Math.max(height1,height3,height2)+10);
			$('body').height(Math.max(height1,height3,height2)+10);
		}
		else
		{
			$('html').height(Math.max(height1,height3,height2));
			$('body').height(Math.max(height1,height3,height2));
		}
		
	}
	$(document).ready(function () {
		htmlbodyHeightUpdate()
		$( window ).resize(function() {
			htmlbodyHeightUpdate()
		});
		$( window ).scroll(function() {
			height2 = $('.main').height()
  			htmlbodyHeightUpdate()
		});
	});
	
	
</script>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">

    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
      toastr['<%= type %>']('<%= f[1] %>')
    <% end %>
  </script>
<% end %>