config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'pages#home'

  devise_for :instructors, path: "instructors", controllers: {
      sessions:      'instructors/sessions',
      passwords:     'instructors/passwords',
      registrations: 'instructors/registrations'
    }, path_names: { sign_up: 'touroku'}
    
  devise_for :members, controllers: {
    sessions:      'members/sessions',
    passwords:     'members/passwords',
    registrations: 'members/registrations'
  }
  
  resources :instructors, only: [:show]
  resources :members, only: [:show]
  
  resources :courses do
    resources :sections
    resources :subscriptions, only: [:create]
  end
  
  get '/purchase_history' => 'subscriptions#purchase_history'
end

app/views/layouts/_dashboardheader.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
    data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Anellotec', root_path, { :class=>"navbar-brand" } %>
    </div>
    <div id="navbar" class="navbar-collapse collapse right">
      <ul class="nav navbar-nav navbar-right">
        <% if (instructor_signed_in?) %>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_instructor), class: "img-circle avatar-small" %>
              <%= current_instructor.fullname %>
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "HOME", root_path %></li>
                <li><%= link_to 'ダッシュボードヘ', courses_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'ログアウト', destroy_instructor_session_path, method: :delete %></li>
              </ul>
            </li>
        <% end %>
        
        <% if (member_signed_in?) %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_member), class: "img-circle avatar-small" %>
              <%= current_member.fullname %>
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "HOME", root_path %></li>
                <li><%= link_to 'ダッシュボードヘ', purchase_history_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'ログアウト', destroy_member_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>

      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="col-md-6 footer-text">
      <h2>AnelloTecについて</h2>
      <p>AnelloTecは、イタリア語の「Anello（輪）」と「Tecnologia（テクノロジー）」を組み合わせた「テクノロジーの輪」を現す造語です。 本サイトでは、様々なテクノロジーを動画やテキストで学ぶことができます。このサイトを通して、輪に加わるエンジニアが増えることを望みます。</p>
    </div>
    <div class="col-md-3 footer-text">
      <h2>Navigate</h2>
    プライバシーポリシー
    利用規約
	    <li><%= link_to 'ログイン（講師）', new_instructor_session_path %></li>
	  </div>
    <div class="col-md-3">Social
    
    Twitter(準備中)

  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav id="menu-wrap" class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
    data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Anellotec', root_path, { :class=>"navbar-brand" } %>
    </div>
    <div id="navbar menu" class="navbar-collapse collapse right">
      <ul class="nav navbar-nav navbar-right">
        <% if (!instructor_signed_in? && !member_signed_in?) %>
          <li><%= link_to '会員登録', new_member_registration_path %></li>
          <li><%= link_to 'ログイン', new_member_session_path %></li>
        <% else %>
          <% if (instructor_signed_in?) %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_instructor), class: "img-circle avatar-small" %>
              <%= current_instructor.fullname %>
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "HOME", root_path %></li>
                <li><%= link_to 'ダッシュボードヘ', courses_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'ログアウト', destroy_instructor_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
          <% if (member_signed_in?) %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_member), class: "img-circle avatar-small" %>
              <%= current_member.fullname %>
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "HOME", root_path %></li>
                <li><%= link_to 'ダッシュボードヘ', purchase_history_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'ログアウト', destroy_member_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
        <% end %>

      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<script>
var menuHeight = $("#menu-wrap").height();
var startPos = 0;
$(window).scroll(function(){
  var currentPos = $(this).scrollTop();
  if (currentPos > startPos) {
    if($(window).scrollTop() >= 200) {
      $("#menu-wrap").css("top", "-" + menuHeight + "px");
    }
  } else {
    $("#menu-wrap").css("top", 0 + "px");
  }
  startPos = currentPos;
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anellotec</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'shared/message' %>
  
    <%= yield %>
    
    <%= render 'layouts/footer' %>
  </body>
</html>